### ISSUE TITLE
в инструкции по сборке ряд неточностей

### ISSUE THREAD

**Issue by airo** [tarantool/migrate#4]
Ubuntu 16.04

1. чекаутить код нужно с сабмодулями, обычный git clone забирает без libsmall и проч из папки third_party
git clone --recursive  https://github.com/bigbes/migrate.git

2. после чего указано
cd http && cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo

хотя по умолчанию счекаутится в migrate

3. при сборке возникает ошибка
/usr/include/tarantool/module.h:58:56: fatal error: lua.h: No such file or directory
пришлось поправить путь до lua.h файла на 
#include <tarantool/lua.h>  /* does not have extern C wrappers */

но это похоже косяк в пакете tarantool-dev

**Comment by Totktonada** [comment]
Closed in favor of the linked issues.
